version: 1
disable_existing_loggers: True
formatters:
    default:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%d.%m.%Y %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: default
        stream  : ext://sys.stdout
    file:
        class: logging.handlers.RotatingFileHandler
        filename: log.log
        level: INFO
        formatter: default        
        maxBytes: 1048576
        backupCount: 3

loggers:
    root:
        level: DEBUG
        handlers: [console, file]
    apscheduler.executors:
        level: WARNING
        handlers: [console]


